services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mci}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-mci}"]
      interval: 5s
      timeout: 5s
      retries: 5

  s3:
    image: chrislusf/seaweedfs
    ports:
      - "9333:9333"
      - "8080:8080"
      - "8333:8333"
    command: "server -s3 -dir=/data"
    volumes:
      - s3_data:/data

  migrations:
    build: .
    container_name: mci_migrations
    command: diesel migration run
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-mci}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  mci:
    build: .
    container_name: mci
    ports:
      - "7687:7687"
    environment:
      MCI_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-mci}
      MCI_S3_URL: ${MCI_S3_URL:-http://s3:8333}
    volumes:
      - .:/app
      - certs:/app/certs
    depends_on:
      migrations:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      s3:
        condition: service_started

volumes:
  certs:
  pg_data:
  s3_data:
